language: node_js	
sudo: required	
dist: trusty	
before_script:	
  - npm install -g web-component-tester	
  - npm install bower	
  - 'export PATH=$PWD/node_modules/.bin:$PATH'	
  - bower install	
  - bower install web-component-tester	
node_js: 8	
addons:	
  firefox: latest	
  apt:	
    sources:	
      - google-chrome	
    packages:	
      - google-chrome-stable	
script:	
  - xvfb-run npm run wct:no-sauce	
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then npm run wct:sauce-only; fi"